# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Stanislas Bonifetto
title: Lead Software Engineer
email: stanislas.bonifetto@gmail.com
# website: stanislasbonifetto.github.com

# Social links
# twitter_username: facespics
github_username:  stanislasbonifetto
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: stanislasbonifetto
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a passionate **Lead Software Engineer and Agile/Lean** advocate with 20+ years of experience in startups and large companies. 
  Using my strong agile background and excellent technical skills I lead, mentor, and coach teams to build the software of the future with the right technologies used in the right way. 
  **I solve complex problems decomposing in simple architectures and code** easy to read, and designed with clean code, hexagonal architecture, and TDD. 
  I am eager to be part of teams and use my experience to help: 
  - building complex products from scratch
  - **mentoring developers** on Lean and Agile methodologies and principles, pair programming, clean code, TDD, BDD, microservices, hexagonal and reactive architecture, domain-driven design, event-driven and distributed systems
  - **keeping the codebase clean and production-ready**
  - **observing the systems by the Golden Signals** - Latency, Traffic, Errors, and Saturation
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
