# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Stanislas Bonifetto
title: Cloud software engineering
email: stanislas.bonifetto@gmail.com
# website: stanislasbonifetto.github.com

# Social links
# twitter_username: facespics
github_username:  stanislasbonifetto
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: stanislasbonifetto
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Java Cloud Software Engineer with 15+ years of experience in development and growing new products.
  My experience in software development goes beyond coding, I appreciate and understand full systems starting from UX passing through development and coming to architecture. My excellent object oriented design, analysis, and testing skills allow me to build applications from the ground up and become productive in a project quickly.
  Lean and agile principles are the pillars of my work flow model, both when I am working individually or leading a group.
  I am able to communicate effectively with technical and non­ technical people at all levels, and I am at ease working on my own or within a team.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
